name: publish to nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: build, pack and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Ini.Net/Ini.Net.csproj
        VERSION_FILE_PATH: src/Ini.Net/Ini.Net.nuspec
        VERSION_REGEX: <version>(.*)<\/version>
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
